# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checks out $GITHUB_WORKSPACE repository 
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B clean package -DskipTests --file selenium_test/pom.xml
