# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Selenium Tests

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
           mvn -B test --file selenium_test/pom.xml
           echo 'maven build `date`'
    - name: Commit files # commit the output folder
      run: |
          git config --local user.email "35377739+sayantandey@users.noreply.github.com"
          git config --local user.name "Sayantan Dey's bot"
          git add selenium_test/test-results
          git commit -m "Test Results at `date`"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        # branch: ignore if main
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
