# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Selenium Tests

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
           mvn -B test --file selenium_test/pom.xml
           echo 'maven build `date`'
    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: sayantandey
        author_email: syaintandey@gmail.com
        message: "Your commit message"
        add: "selenium_test/test-results"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
