# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Selenium Tests

on:
  push:
    branches: [ main , dev ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Execute Test Suite With Maven
      run: |
           mvn -B test --file selenium_test/pom.xml
           echo 'Test execution started'
    - name: Save Static File
      uses: actions/upload-artifact@v3
      with:
          name: Test-Results-Screenshots-${{ github.run_id }}
          path: selenium_test/target/output           
    - uses: actions/checkout@v2
    - run: |
        git status
        git config --local user.email "$(git log --format='%ae' HEAD^!)"
        git config --local user.name "$(git log --format='%an' HEAD^!)"
        git add .
        git push
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
